FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN mkdir -p /app/data
ENV DATABASE_PATH=/app/data/dev.db
RUN npx @better-auth/cli generate -y
RUN npx @better-auth/cli migrate -y
EXPOSE 3000
CMD ["npm", "run", "dev"]
